apiVersion: v1
kind: Pod
metadata:
  name: hello-volume
spec:
  containers:
  - image: busybox
    name: busybox1
    command:
    - /bin/sh
    - -c
    - "while true; do echo hello; sleep 10; done"
    volumeMounts:
    - name: hello-volume
      mountPath: /test-pd
  - image: busybox
    name: busybox2
    command:
    - /bin/sh
    - -c
    - "while true; do echo hello; sleep 10; done"
    volumeMounts:
    - name: hello-volume
      mountPath: /test-pd
  volumes:
  - name: hello-volume
    hostPath:
      path: /root/data