kind: pipline
name: k8s-practice

steps:
# ssh pipelines deploy the application on my k8s cluster
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 202.120.40.8
    username: root
    port: 30350
    password:
      from_secret: password
    script:
      - cd /drone/src
      - ls
  when:
    branch:
    - master