apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: default

secretGenerator:
- name: wordpress-secrets
  files:
  - "secret/db-password"
  type: Opaque