apiVersion: v1
kind: Service
metadata:
  name:  wordpress-service
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - name: wordpress-service
    port: 31000
    nodePort: 31000
    targetPort: http-port
    protocol: TCP