apiVersion: v1
kind: Service
metadata:
  name:  database-service
spec:
  selector:
    app: database
  type: NodePort
  ports:
  - name: database-service
    port: 3306
    targetPort: mysql-port
    protocol: TCP