apiVersion: v1
kind: Service
metadata:
  name:  helloword-service
spec:
  selector:
    app: helloword
  type: NodePort
  ports:
  - name: helloword-service
    port: 3000
    nodePort: 31001
    protocol: TCP