apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database-deployment.yaml
- database-service.yaml
- helloworld-deployment.yaml
- helloworld-service.yaml

namespace: default

secretGenerator:
- name: helloworld-secrets
  files:
  - "secret/username"
  - "secret/password"
  - "secret/rootPassword"
  - "secret/database"
  type: Opaque 