apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac/clusterRole.yml
  - rbac/serviceAccount.yml
  - rbac/clusterRoleBinding.yml
  - deployment.yml
  - service.yml

namespace: default

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml