apiVersion: v1
kind: Service
metadata:
  name: prometheus-service # service name
spec:
  selector:
    name: prometheus
  type: NodePort
  ports:
  - name: prometheus-port
    port: 9090
    targetPort: 9090
    nodePort: 30351
    protocol: TCP
