kind: Service
apiVersion: v1
metadata:
  name: argus-amazon
  namespace: default
  labels:
    name: argus-amazon
spec:
  selector:
    name: argus-amazon
  type: NodePort
  ports:
  - name: argus-amazon
    port: 8088
    targetPort: 8088
    nodePort: 30357