apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - frontend-deployment.yml
  - frontend-service.yml
  - jd-deployment.yml
  - jd-hpa.yml
  - jd-service.yml
  - amazon-deployment.yml
  - amazon-service.yml
  - mail-deployment.yml
  - mail-service.yml