apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namespace: default

secretGenerator:
- name: db-secrets
  files:
  - "secret/username"
  - "secret/password"
  type: Opaque