apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus # Gllbal, no need to specify namespace
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - nodes/proxy
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - metrics
    verbs:
      - get