apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: true
spec:
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP